version: '3.9'
services:
  postgres:
    container_name: nakama-simple-postgres
    image: postgres:14
    restart: unless-stopped
    environment:
      - POSTGRES_DB=nakama
      - POSTGRES_USER=nakama
      - POSTGRES_PASSWORD=nakama_pass
    volumes:
      - ./postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "nakama", "-d", "nakama"]
      interval: 10s
      timeout: 5s
      retries: 5
    expose:
      - "8080"
      - "5432"
    ports:
      - "5432:5432"
      - "8080:8080"

  nakama:
    container_name: nakama-simple
    image: registry.heroiclabs.com/heroiclabs/nakama:3.22.0
    env_file:
      - .env
    entrypoint:
      - "/bin/sh"
      - "-ecx"
      - >
          /nakama/nakama migrate up --database.address ${DATABASE_URL} &&
          exec /nakama/nakama --name nakama1 --database.address ${DATABASE_URL} --logger.level INFO --session.token_expiry_sec 7200 --runtime.path "/nakama/data/modules" --runtime.js_entrypoint "main.js"
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./data:/nakama/data
    expose:
      - "7349"
      - "7350"
      - "7351"
    ports:
      - "7349:7349"
      - "7350:7350"
      - "7351:7351"
    healthcheck:
      test: ["CMD", "/nakama/nakama", "healthcheck"]
      interval: 10s
      timeout: 5s
      retries: 5
